version: '3.4'

services:
  databaseeditor:
    image: ${DOCKER_REGISTRY-}databaseeditor
    build:
      context: .
      dockerfile: DatabaseEditor/Dockerfile
    ports:
      - "5000:80"                     
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=MyDatabase;Username=postgres;Password=admin
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: MyDatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: